/**
 * PhotoSignature Sales Dummy Data Seeder
 */

import { MongoClient, Decimal128 } from 'mongodb';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { existsSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config({ path: join(__dirname, '.env') });

const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.MONGODB_DB_NAME || 'photosignature';
const CERT_PATH = process.env.MONGODB_CERT_PATH;

// 더미 데이터 생성
const dummySales = [
  {
    timestamp: new Date('2025-01-15T10:30:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115001', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_001', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T11:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_002', name: 'Gangnam_Unit2' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('1000'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_002', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T12:30:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115002', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'BEAUTY', frameId: 'frame_003', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_KAKAO_2025', name: 'Kakao Friends 2025', characterId: 'RYAN', characterName: 'Ryan', revenue: { storeRate: 0.30, corpRate: 0.50, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T14:00:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('500'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.12'),
    amountKRW: Decimal128.fromString('4560'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115003', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_004', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T15:30:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('600'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.12'),
    amountKRW: Decimal128.fromString('5472'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'CACHED',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('50'), coupon: Decimal128.fromString('0') },
    product: { type: 'AI', frameId: 'frame_005', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    services: { beauty: { used: false, fee: Decimal128.fromString('0') }, ai: { used: true, fee: Decimal128.fromString('100') } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T16:00:00Z'),
    store: { id: 'STORE_004', name: '호치민점', groupId: 'GROUP_VIETNAM', groupName: '베트남지점' },
    device: { id: 'KIOSK_005', name: 'HCM_Unit1' },
    country: { code: 'VNM', name: 'Vietnam' },
    amount: Decimal128.fromString('100000'),
    currency: 'VND',
    exchangeRate: Decimal128.fromString('0.054'),
    amountKRW: Decimal128.fromString('5400'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115004', pgProvider: 'VNPAY' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_006', frameCategory: '3CUT', printCount: 1, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T17:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115005', pgProvider: 'NICE' },
    status: 'REFUNDED',
    refundedAt: new Date('2025-01-15T18:00:00Z'),
    refundReason: '고객 요청',
    refundedBy: 'admin@photosignature.com',
    refundSnapshot: { originalAmount: Decimal128.fromString('5000'), originalAmountKRW: Decimal128.fromString('5000'), originalStatus: 'COMPLETED' },
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_007', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T18:30:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('4000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('4000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115006', pgProvider: 'NICE' },
    status: 'FAILED',
    failedAt: new Date('2025-01-15T18:30:05Z'),
    failReason: 'Card declined',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_008', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T19:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_002', name: 'Gangnam_Unit2' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('8000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('8000'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250115007', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('500'), couponCode: 'WINTER2025' },
    product: { type: 'PHOTO', frameId: 'frame_009', frameCategory: '8CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_KAKAO_2025', name: 'Kakao Friends 2025', characterId: 'APEACH', characterName: 'Apeach', revenue: { storeRate: 0.30, corpRate: 0.50, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-15T20:00:00Z'),
    store: { id: 'STORE_005', name: 'LA점', groupId: 'GROUP_USA', groupName: '미국지점' },
    device: { id: 'KIOSK_006', name: 'LA_Unit1' },
    country: { code: 'USA', name: 'USA' },
    amount: Decimal128.fromString('4.99'),
    currency: 'USD',
    exchangeRate: Decimal128.fromString('1450.50'),
    amountKRW: Decimal128.fromString('7237.99'),
    rateDate: new Date('2025-01-15'),
    rateSource: 'API_FALLBACK',
    payment: { type: 'CARD', receiptNo: 'R20250115008', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'FORTUNE', frameId: 'frame_010', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  // 추가 더미 데이터 10개
  {
    timestamp: new Date('2025-01-16T09:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('7000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('7000'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116001', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_011', frameCategory: '6CUT', printCount: 3, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T10:30:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5500'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5500'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('500'), coupon: Decimal128.fromString('0') },
    product: { type: 'BEAUTY', frameId: 'frame_012', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T11:15:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('700'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.15'),
    amountKRW: Decimal128.fromString('6405'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116002', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'AI', frameId: 'frame_013', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    services: { beauty: { used: false, fee: Decimal128.fromString('0') }, ai: { used: true, fee: Decimal128.fromString('150') } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T12:00:00Z'),
    store: { id: 'STORE_006', name: '부산 서면점', groupId: 'GROUP_BUSAN', groupName: '부산지점' },
    device: { id: 'KIOSK_007', name: 'Busan_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6000'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116003', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_014', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_SANRIO_2025', name: 'Sanrio Characters 2025', characterId: 'KUROMI', characterName: 'Kuromi', revenue: { storeRate: 0.25, corpRate: 0.55, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T13:30:00Z'),
    store: { id: 'STORE_004', name: '호치민점', groupId: 'GROUP_VIETNAM', groupName: '베트남지점' },
    device: { id: 'KIOSK_005', name: 'HCM_Unit1' },
    country: { code: 'VNM', name: 'Vietnam' },
    amount: Decimal128.fromString('120000'),
    currency: 'VND',
    exchangeRate: Decimal128.fromString('0.055'),
    amountKRW: Decimal128.fromString('6600'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116004', pgProvider: 'VNPAY' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_015', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T14:45:00Z'),
    store: { id: 'STORE_005', name: 'LA점', groupId: 'GROUP_USA', groupName: '미국지점' },
    device: { id: 'KIOSK_006', name: 'LA_Unit1' },
    country: { code: 'USA', name: 'USA' },
    amount: Decimal128.fromString('5.99'),
    currency: 'USD',
    exchangeRate: Decimal128.fromString('1452.30'),
    amountKRW: Decimal128.fromString('8699.28'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116005', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_016', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T15:20:00Z'),
    store: { id: 'STORE_007', name: '대구점', groupId: 'GROUP_DAEGU', groupName: '대구지점' },
    device: { id: 'KIOSK_008', name: 'Daegu_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('1000'), couponCode: 'NEWYEAR2025' },
    product: { type: 'PHOTO', frameId: 'frame_017', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T16:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_002', name: 'Gangnam_Unit2' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('3000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('3000'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116006', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_018', frameCategory: '4CUT', printCount: 1, isAdditionalPrint: true },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T17:30:00Z'),
    store: { id: 'STORE_008', name: '오사카점', groupId: 'GROUP_OSAKA', groupName: '오사카지점' },
    device: { id: 'KIOSK_009', name: 'Osaka_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('550'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.18'),
    amountKRW: Decimal128.fromString('5049'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116007', pgProvider: 'STRIPE' },
    status: 'REFUNDED',
    refundedAt: new Date('2025-01-16T19:00:00Z'),
    refundReason: '기기 오류로 인한 환불',
    refundedBy: 'staff@photosignature.com',
    refundSnapshot: { originalAmount: Decimal128.fromString('550'), originalAmountKRW: Decimal128.fromString('5049'), originalStatus: 'COMPLETED' },
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_019', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-16T18:45:00Z'),
    store: { id: 'STORE_006', name: '부산 서면점', groupId: 'GROUP_BUSAN', groupName: '부산지점' },
    device: { id: 'KIOSK_007', name: 'Busan_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('9000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('9000'),
    rateDate: new Date('2025-01-16'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250116008', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('1000'), coupon: Decimal128.fromString('0') },
    product: { type: 'FORTUNE', frameId: 'frame_020', frameCategory: '8CUT', printCount: 4, isAdditionalPrint: false },
    popup: { id: 'POPUP_DISNEY_2025', name: 'Disney 100th Anniversary', characterId: 'MICKEY', characterName: 'Mickey Mouse', revenue: { storeRate: 0.20, corpRate: 0.50, licenseRate: 0.30 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  // 추가 더미 데이터 30개 (2025-01-17 ~ 2025-01-19)
  {
    timestamp: new Date('2025-01-17T09:15:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117001', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_021', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T10:00:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6000'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'BEAUTY', frameId: 'frame_022', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T10:45:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('600'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.20'),
    amountKRW: Decimal128.fromString('5520'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117002', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_023', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T11:30:00Z'),
    store: { id: 'STORE_006', name: '부산 서면점', groupId: 'GROUP_BUSAN', groupName: '부산지점' },
    device: { id: 'KIOSK_007', name: 'Busan_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('7000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('7000'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117003', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('500'), coupon: Decimal128.fromString('0') },
    product: { type: 'AI', frameId: 'frame_024', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    services: { beauty: { used: false, fee: Decimal128.fromString('0') }, ai: { used: true, fee: Decimal128.fromString('200') } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T12:15:00Z'),
    store: { id: 'STORE_004', name: '호치민점', groupId: 'GROUP_VIETNAM', groupName: '베트남지점' },
    device: { id: 'KIOSK_005', name: 'HCM_Unit1' },
    country: { code: 'VNM', name: 'Vietnam' },
    amount: Decimal128.fromString('90000'),
    currency: 'VND',
    exchangeRate: Decimal128.fromString('0.054'),
    amountKRW: Decimal128.fromString('4860'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_025', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T13:00:00Z'),
    store: { id: 'STORE_005', name: 'LA점', groupId: 'GROUP_USA', groupName: '미국지점' },
    device: { id: 'KIOSK_006', name: 'LA_Unit1' },
    country: { code: 'USA', name: 'USA' },
    amount: Decimal128.fromString('6.99'),
    currency: 'USD',
    exchangeRate: Decimal128.fromString('1455.00'),
    amountKRW: Decimal128.fromString('10170.45'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117004', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'FORTUNE', frameId: 'frame_026', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T14:30:00Z'),
    store: { id: 'STORE_007', name: '대구점', groupId: 'GROUP_DAEGU', groupName: '대구지점' },
    device: { id: 'KIOSK_008', name: 'Daegu_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5500'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5500'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117005', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_027', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_SANRIO_2025', name: 'Sanrio Characters 2025', characterId: 'MELODY', characterName: 'My Melody', revenue: { storeRate: 0.25, corpRate: 0.55, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T15:15:00Z'),
    store: { id: 'STORE_008', name: '오사카점', groupId: 'GROUP_OSAKA', groupName: '오사카지점' },
    device: { id: 'KIOSK_009', name: 'Osaka_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('650'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.20'),
    amountKRW: Decimal128.fromString('5980'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117006', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_028', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T16:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_002', name: 'Gangnam_Unit2' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('8000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('8000'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117007', pgProvider: 'NICE' },
    status: 'FAILED',
    failedAt: new Date('2025-01-17T16:00:05Z'),
    failReason: 'Payment timeout',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_029', frameCategory: '8CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-17T17:30:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-17'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250117008', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('500'), couponCode: 'PHOTO500' },
    product: { type: 'PHOTO', frameId: 'frame_030', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T09:00:00Z'),
    store: { id: 'STORE_009', name: '제주점', groupId: 'GROUP_JEJU', groupName: '제주지점' },
    device: { id: 'KIOSK_010', name: 'Jeju_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6000'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118001', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_031', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T09:45:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('7000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('7000'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('1000'), coupon: Decimal128.fromString('0') },
    product: { type: 'BEAUTY', frameId: 'frame_032', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T10:30:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('800'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.18'),
    amountKRW: Decimal128.fromString('7344'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118002', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'AI', frameId: 'frame_033', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    services: { beauty: { used: true, fee: Decimal128.fromString('100') }, ai: { used: true, fee: Decimal128.fromString('200') } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T11:15:00Z'),
    store: { id: 'STORE_006', name: '부산 서면점', groupId: 'GROUP_BUSAN', groupName: '부산지점' },
    device: { id: 'KIOSK_007', name: 'Busan_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118003', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_034', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T12:00:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6500'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6500'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118004', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_035', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T13:30:00Z'),
    store: { id: 'STORE_004', name: '호치민점', groupId: 'GROUP_VIETNAM', groupName: '베트남지점' },
    device: { id: 'KIOSK_005', name: 'HCM_Unit1' },
    country: { code: 'VNM', name: 'Vietnam' },
    amount: Decimal128.fromString('110000'),
    currency: 'VND',
    exchangeRate: Decimal128.fromString('0.054'),
    amountKRW: Decimal128.fromString('5940'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118005', pgProvider: 'VNPAY' },
    status: 'REFUNDED',
    refundedAt: new Date('2025-01-18T15:00:00Z'),
    refundReason: '인쇄 품질 불량',
    refundedBy: 'staff_vn@photosignature.com',
    refundSnapshot: { originalAmount: Decimal128.fromString('110000'), originalAmountKRW: Decimal128.fromString('5940'), originalStatus: 'COMPLETED' },
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_036', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T14:15:00Z'),
    store: { id: 'STORE_005', name: 'LA점', groupId: 'GROUP_USA', groupName: '미국지점' },
    device: { id: 'KIOSK_006', name: 'LA_Unit1' },
    country: { code: 'USA', name: 'USA' },
    amount: Decimal128.fromString('4.99'),
    currency: 'USD',
    exchangeRate: Decimal128.fromString('1458.00'),
    amountKRW: Decimal128.fromString('7275.42'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118006', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_037', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T15:00:00Z'),
    store: { id: 'STORE_007', name: '대구점', groupId: 'GROUP_DAEGU', groupName: '대구지점' },
    device: { id: 'KIOSK_008', name: 'Daegu_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('6000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('6000'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118007', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_038', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_KAKAO_2025', name: 'Kakao Friends 2025', characterId: 'TUBE', characterName: 'Tube', revenue: { storeRate: 0.30, corpRate: 0.50, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T16:30:00Z'),
    store: { id: 'STORE_008', name: '오사카점', groupId: 'GROUP_OSAKA', groupName: '오사카지점' },
    device: { id: 'KIOSK_009', name: 'Osaka_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('700'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.18'),
    amountKRW: Decimal128.fromString('6426'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('50'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_039', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-18T17:15:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('10000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('10000'),
    rateDate: new Date('2025-01-18'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250118008', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'FORTUNE', frameId: 'frame_040', frameCategory: '8CUT', printCount: 4, isAdditionalPrint: false },
    popup: { id: 'POPUP_DISNEY_2025', name: 'Disney 100th Anniversary', characterId: 'DONALD', characterName: 'Donald Duck', revenue: { storeRate: 0.20, corpRate: 0.50, licenseRate: 0.30 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T09:30:00Z'),
    store: { id: 'STORE_001', name: '강남점', groupId: 'GROUP_GANGNAM', groupName: '강남지점' },
    device: { id: 'KIOSK_001', name: 'Gangnam_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119001', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_041', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T10:15:00Z'),
    store: { id: 'STORE_009', name: '제주점', groupId: 'GROUP_JEJU', groupName: '제주지점' },
    device: { id: 'KIOSK_010', name: 'Jeju_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('7000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('7000'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('1000'), couponCode: 'JEJU1000' },
    product: { type: 'BEAUTY', frameId: 'frame_042', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T11:00:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('550'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.22'),
    amountKRW: Decimal128.fromString('5071'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119002', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_043', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T11:45:00Z'),
    store: { id: 'STORE_003', name: '도쿄 시부야점', groupId: 'GROUP_TOKYO', groupName: '도쿄지점' },
    device: { id: 'KIOSK_004', name: 'Tokyo_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('680'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.22'),
    amountKRW: Decimal128.fromString('6269.60'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119003', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'AI', frameId: 'frame_044', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    services: { beauty: { used: false, fee: Decimal128.fromString('0') }, ai: { used: true, fee: Decimal128.fromString('100') } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T12:30:00Z'),
    store: { id: 'STORE_006', name: '부산 서면점', groupId: 'GROUP_BUSAN', groupName: '부산지점' },
    device: { id: 'KIOSK_007', name: 'Busan_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5500'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5500'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119004', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('500'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_045', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T13:15:00Z'),
    store: { id: 'STORE_004', name: '호치민점', groupId: 'GROUP_VIETNAM', groupName: '베트남지점' },
    device: { id: 'KIOSK_005', name: 'HCM_Unit1' },
    country: { code: 'VNM', name: 'Vietnam' },
    amount: Decimal128.fromString('100000'),
    currency: 'VND',
    exchangeRate: Decimal128.fromString('0.055'),
    amountKRW: Decimal128.fromString('5500'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CASH' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_046', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T14:00:00Z'),
    store: { id: 'STORE_005', name: 'LA점', groupId: 'GROUP_USA', groupName: '미국지점' },
    device: { id: 'KIOSK_006', name: 'LA_Unit1' },
    country: { code: 'USA', name: 'USA' },
    amount: Decimal128.fromString('7.99'),
    currency: 'USD',
    exchangeRate: Decimal128.fromString('1460.00'),
    amountKRW: Decimal128.fromString('11665.40'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119005', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'FORTUNE', frameId: 'frame_047', frameCategory: '6CUT', printCount: 3, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T15:30:00Z'),
    store: { id: 'STORE_007', name: '대구점', groupId: 'GROUP_DAEGU', groupName: '대구지점' },
    device: { id: 'KIOSK_008', name: 'Daegu_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('5000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('5000'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119006', pgProvider: 'NICE' },
    status: 'FAILED',
    failedAt: new Date('2025-01-19T15:30:10Z'),
    failReason: 'Insufficient funds',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_048', frameCategory: '4CUT', printCount: 2, isAdditionalPrint: false },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T16:15:00Z'),
    store: { id: 'STORE_008', name: '오사카점', groupId: 'GROUP_OSAKA', groupName: '오사카지점' },
    device: { id: 'KIOSK_009', name: 'Osaka_Unit1' },
    country: { code: 'JPN', name: 'Japan' },
    amount: Decimal128.fromString('750'),
    currency: 'JPY',
    exchangeRate: Decimal128.fromString('9.22'),
    amountKRW: Decimal128.fromString('6915'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119007', pgProvider: 'STRIPE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_049', frameCategory: '6CUT', printCount: 2, isAdditionalPrint: false },
    popup: { id: 'POPUP_SANRIO_2025', name: 'Sanrio Characters 2025', characterId: 'CINNAMOROLL', characterName: 'Cinnamoroll', revenue: { storeRate: 0.25, corpRate: 0.55, licenseRate: 0.20 } },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    timestamp: new Date('2025-01-19T17:00:00Z'),
    store: { id: 'STORE_002', name: '홍대점', groupId: 'GROUP_HONGDAE', groupName: '홍대지점' },
    device: { id: 'KIOSK_003', name: 'Hongdae_Unit1' },
    country: { code: 'KOR', name: 'Korea' },
    amount: Decimal128.fromString('3000'),
    currency: 'KRW',
    exchangeRate: Decimal128.fromString('1'),
    amountKRW: Decimal128.fromString('3000'),
    rateDate: new Date('2025-01-19'),
    rateSource: 'FIREBASE',
    payment: { type: 'CARD', receiptNo: 'R20250119008', pgProvider: 'NICE' },
    status: 'COMPLETED',
    discount: { roulette: Decimal128.fromString('0'), coupon: Decimal128.fromString('0') },
    product: { type: 'PHOTO', frameId: 'frame_050', frameCategory: '4CUT', printCount: 1, isAdditionalPrint: true },
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

async function main() {
  console.log('='.repeat(60));
  console.log('  PhotoSignature Sales Seeder');
  console.log('='.repeat(60));

  const certPath = CERT_PATH ? join(__dirname, CERT_PATH) : null;

  const client = new MongoClient(MONGODB_URI, {
    tls: true,
    tlsCertificateKeyFile: certPath,
  });

  try {
    await client.connect();
    console.log('\n[CONNECTED] MongoDB Atlas');

    const db = client.db(DB_NAME);
    const sales = db.collection('sales');

    const result = await sales.insertMany(dummySales);
    console.log(`\n[INSERT] ${result.insertedCount}개 sales 데이터 추가`);

    console.log('\n추가된 데이터 요약:');
    console.log('  - 한국 (KOR): 10건');
    console.log('  - 일본 (JPN): 4건');
    console.log('  - 베트남 (VNM): 2건');
    console.log('  - 미국 (USA): 2건');
    console.log('  - COMPLETED: 16건');
    console.log('  - REFUNDED: 2건');
    console.log('  - FAILED: 1건');

    console.log('\n' + '='.repeat(60));
    console.log('  Seed Complete!');
    console.log('='.repeat(60));

  } catch (err) {
    console.error('\n[ERROR]', err.message);
    process.exit(1);
  } finally {
    await client.close();
  }
}

main();
